#!/bin/bash
# AI Fortress — Phase 1 install (host services).
# Creates the bifrost system user, fortress group, /etc/ai-fortress, installs
# all templates + helpers + units + nft fragment. Does NOT start services or
# load nft rules — that's start-phase1.sh after upstream.env has real keys.
#
# Run as: sudo bash install-phase1.sh
#
# Idempotent: re-running should be safe. Migrates a pre-existing 'litellm'
# user (from earlier LiteLLM-era installs) to 'bifrost'.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
INVOKER="${SUDO_USER:-$USER}"
[[ "$EUID" -ne 0 ]] && { echo "must be run as root (use sudo)" >&2; exit 1; }

say() { printf '\n=== %s ===\n' "$*"; }

# -------------------------------------------------------------------------
say "1. bifrost system user (UID 1500)"
if id bifrost >/dev/null 2>&1; then
  echo "bifrost user already exists"
elif id litellm >/dev/null 2>&1; then
  # Migrate from the LiteLLM-era user
  usermod -l bifrost litellm
  echo "renamed litellm user to bifrost"
else
  useradd --system --no-create-home --shell /usr/sbin/nologin --uid 1500 bifrost
  echo "created bifrost user (UID $(id -u bifrost))"
fi

# -------------------------------------------------------------------------
say "2. fortress group + add invoker"
if getent group fortress >/dev/null; then
  echo "fortress group already exists"
else
  groupadd -r fortress
  echo "created fortress group"
fi
if id -nG "$INVOKER" | tr ' ' '\n' | grep -qx fortress; then
  echo "$INVOKER already in fortress group"
else
  usermod -aG fortress "$INVOKER"
  echo "added $INVOKER to fortress group (effective on next login)"
fi

# -------------------------------------------------------------------------
say "3. /etc/ai-fortress directory"
install -d -m 0755 -o root -g root /etc/ai-fortress

# -------------------------------------------------------------------------
say "4. /etc/ai-fortress/upstream.env"
if [[ -f /etc/ai-fortress/upstream.env ]]; then
  echo "upstream.env already exists"
  # Migrate from LiteLLM-era format if needed: make sure BIFROST_* are present.
  if ! grep -q '^BIFROST_ADMIN_PASSWORD=' /etc/ai-fortress/upstream.env; then
    NEW_PW="$(openssl rand -base64 32 | tr -d '\n=' | tr '+/' '-_')"
    {
      echo ""
      echo "# Added by install-phase1.sh (Bifrost migration)"
      echo "BIFROST_ADMIN_USERNAME=fortress-admin"
      echo "BIFROST_ADMIN_PASSWORD=$NEW_PW"
    } >> /etc/ai-fortress/upstream.env
    echo "appended BIFROST_ADMIN_USERNAME/PASSWORD to upstream.env"
  fi
else
  ADMIN_PW="$(openssl rand -base64 32 | tr -d '\n=' | tr '+/' '-_')"
  umask 077
  cat > /etc/ai-fortress/upstream.env <<EOF
# Generated by install-phase1.sh on $(date -Iseconds).
# YOU MUST FILL IN the two REPLACE-ME values before starting services.
ANTHROPIC_UPSTREAM_KEY=sk-ant-REPLACE-ME
OPENAI_UPSTREAM_KEY=sk-REPLACE-ME

# Bifrost governance API (admin basic-auth, generated automatically)
BIFROST_ADMIN_USERNAME=fortress-admin
BIFROST_ADMIN_PASSWORD=$ADMIN_PW
EOF
  chmod 0600 /etc/ai-fortress/upstream.env
  chown root:root /etc/ai-fortress/upstream.env
  echo "wrote /etc/ai-fortress/upstream.env (admin password generated; upstreams need editing)"
fi

# -------------------------------------------------------------------------
say "5. /etc/ai-fortress/bifrost-config.json"
install -m 0644 -o root -g root \
  "$REPO_DIR/host/bifrost-config.json" \
  /etc/ai-fortress/bifrost-config.json

# -------------------------------------------------------------------------
say "6. helper scripts in /usr/local/sbin"
install -m 0750 -o root -g fortress "$REPO_DIR/host/fortress-mint"   /usr/local/sbin/fortress-mint
install -m 0750 -o root -g fortress "$REPO_DIR/host/fortress-revoke" /usr/local/sbin/fortress-revoke
install -m 0750 -o root -g root     "$REPO_DIR/host/fortress-sweep"  /usr/local/sbin/fortress-sweep

# -------------------------------------------------------------------------
say "7. sudoers dropin (validated)"
visudo -c -f "$REPO_DIR/host/ai-fortress.sudoers"
install -m 0440 -o root -g root "$REPO_DIR/host/ai-fortress.sudoers" /etc/sudoers.d/ai-fortress

# -------------------------------------------------------------------------
say "8. systemd unit files (installed, NOT enabled yet)"
install -m 0644 -o root -g root "$REPO_DIR/host/ai-fortress-bifrost.service"     /etc/systemd/system/
install -m 0644 -o root -g root "$REPO_DIR/host/ai-fortress-vsock-relay.service" /etc/systemd/system/
install -m 0644 -o root -g root "$REPO_DIR/host/ai-fortress-key-sweep.service"   /etc/systemd/system/
install -m 0644 -o root -g root "$REPO_DIR/host/ai-fortress-key-sweep.timer"     /etc/systemd/system/

# Migrate from the LiteLLM-era unit if present
if [[ -f /etc/systemd/system/ai-fortress-litellm.service ]]; then
  echo "removing obsolete ai-fortress-litellm.service"
  systemctl disable --now ai-fortress-litellm.service 2>/dev/null || true
  rm -f /etc/systemd/system/ai-fortress-litellm.service
fi
systemctl daemon-reload

# Stale relay dependency (relay's [Unit] file now points at bifrost; reload picks it up)

# -------------------------------------------------------------------------
say "9. nftables fragment + persistence include"
install -d -m 0755 /etc/nftables.d
install -m 0644 -o root -g root "$REPO_DIR/host/ai-fortress.nft" /etc/nftables.d/ai-fortress.nft

if [[ -f /etc/sysconfig/nftables.conf ]] \
   && ! grep -q '/etc/nftables.d/' /etc/sysconfig/nftables.conf; then
  cp -a /etc/sysconfig/nftables.conf /etc/sysconfig/nftables.conf.bak.preinstall
  printf '\n# AI Fortress fragment (installed by install-phase1.sh)\ninclude "/etc/nftables.d/*.nft"\n' \
    >> /etc/sysconfig/nftables.conf
  echo "appended include directive to /etc/sysconfig/nftables.conf (backup at .bak.preinstall)"
else
  echo "include directive already present (or sysconfig file missing)"
fi

# -------------------------------------------------------------------------
say "Phase 1 install done"
cat <<EOF

Next steps (NOT done by this script):
  1. Edit /etc/ai-fortress/upstream.env and replace the two REPLACE-ME values
     with the real Anthropic + OpenAI upstream keys (root-only file).
       sudo \$EDITOR /etc/ai-fortress/upstream.env
  2. Log out and back in (or 'newgrp fortress') so $INVOKER's group membership
     takes effect — required for sudo -n /usr/local/sbin/fortress-mint to work.
  3. Run the activation step: sudo bash $REPO_DIR/start-phase1.sh
EOF
