#!/bin/bash
# AI Fortress — Phase 1 install (host services).
# Creates litellm system user, fortress group, /etc/ai-fortress, installs all
# templates + helpers + units + nft fragment. Does NOT start services or load
# nft rules — that's a separate step after upstream.env has real keys in it.
#
# Run as: sudo bash install-phase1.sh
#
# Idempotent: re-running should be safe.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
INVOKER="${SUDO_USER:-$USER}"
[[ "$EUID" -ne 0 ]] && { echo "must be run as root (use sudo)" >&2; exit 1; }

say() { printf '\n=== %s ===\n' "$*"; }

# -------------------------------------------------------------------------
say "1. litellm system user (UID 1500)"
if id litellm >/dev/null 2>&1; then
  echo "litellm user already exists"
else
  useradd --system --no-create-home --shell /usr/sbin/nologin --uid 1500 litellm
  echo "created litellm user (UID $(id -u litellm))"
fi

# -------------------------------------------------------------------------
say "2. fortress group + add invoker"
if getent group fortress >/dev/null; then
  echo "fortress group already exists"
else
  groupadd -r fortress
  echo "created fortress group"
fi
if id -nG "$INVOKER" | tr ' ' '\n' | grep -qx fortress; then
  echo "$INVOKER already in fortress group"
else
  usermod -aG fortress "$INVOKER"
  echo "added $INVOKER to fortress group (effective on next login)"
fi

# -------------------------------------------------------------------------
say "3. /etc/ai-fortress directory"
install -d -m 0755 -o root -g root /etc/ai-fortress

# -------------------------------------------------------------------------
say "4. /etc/ai-fortress/upstream.env"
if [[ -f /etc/ai-fortress/upstream.env ]]; then
  echo "upstream.env already exists, leaving it alone"
else
  MASTER_KEY="sk-master-$(openssl rand -base64 32 | tr -d '\n=' | tr '+/' '-_')"
  umask 077
  cat > /etc/ai-fortress/upstream.env <<EOF
# Generated by install-phase1.sh on $(date -Iseconds).
# YOU MUST FILL IN the two REPLACE-ME values before starting services.
ANTHROPIC_UPSTREAM_KEY=sk-ant-REPLACE-ME
OPENAI_UPSTREAM_KEY=sk-REPLACE-ME
LITELLM_MASTER_KEY=$MASTER_KEY
EOF
  chmod 0600 /etc/ai-fortress/upstream.env
  chown root:root /etc/ai-fortress/upstream.env
  echo "wrote /etc/ai-fortress/upstream.env (master key generated; upstreams need editing)"
fi

# -------------------------------------------------------------------------
say "5. /etc/ai-fortress/litellm-config.yaml"
install -m 0644 -o root -g root \
  "$REPO_DIR/host/litellm-config.yaml" \
  /etc/ai-fortress/litellm-config.yaml

# -------------------------------------------------------------------------
say "6. helper scripts in /usr/local/sbin"
install -m 0750 -o root -g fortress "$REPO_DIR/host/fortress-mint"   /usr/local/sbin/fortress-mint
install -m 0750 -o root -g fortress "$REPO_DIR/host/fortress-revoke" /usr/local/sbin/fortress-revoke
install -m 0750 -o root -g root     "$REPO_DIR/host/fortress-sweep"  /usr/local/sbin/fortress-sweep

# -------------------------------------------------------------------------
say "7. sudoers dropin (validated)"
visudo -c -f "$REPO_DIR/host/ai-fortress.sudoers"
install -m 0440 -o root -g root "$REPO_DIR/host/ai-fortress.sudoers" /etc/sudoers.d/ai-fortress

# -------------------------------------------------------------------------
say "8. systemd unit files (installed, NOT enabled yet)"
install -m 0644 -o root -g root "$REPO_DIR/host/ai-fortress-litellm.service"     /etc/systemd/system/
install -m 0644 -o root -g root "$REPO_DIR/host/ai-fortress-vsock-relay.service" /etc/systemd/system/
install -m 0644 -o root -g root "$REPO_DIR/host/ai-fortress-key-sweep.service"   /etc/systemd/system/
install -m 0644 -o root -g root "$REPO_DIR/host/ai-fortress-key-sweep.timer"     /etc/systemd/system/
systemctl daemon-reload

# -------------------------------------------------------------------------
say "9. nftables fragment + persistence include"
install -d -m 0755 /etc/nftables.d
install -m 0644 -o root -g root "$REPO_DIR/host/ai-fortress.nft" /etc/nftables.d/ai-fortress.nft

if [[ -f /etc/sysconfig/nftables.conf ]] \
   && ! grep -q '/etc/nftables.d/' /etc/sysconfig/nftables.conf; then
  cp -a /etc/sysconfig/nftables.conf /etc/sysconfig/nftables.conf.bak.preinstall
  printf '\n# AI Fortress fragment (installed by install-phase1.sh)\ninclude "/etc/nftables.d/*.nft"\n' \
    >> /etc/sysconfig/nftables.conf
  echo "appended include directive to /etc/sysconfig/nftables.conf (backup at .bak.preinstall)"
else
  echo "include directive already present (or sysconfig file missing)"
fi

# -------------------------------------------------------------------------
say "Phase 1 install done"
cat <<EOF

Next steps (NOT done by this script):
  1. Edit /etc/ai-fortress/upstream.env and replace the two REPLACE-ME values
     with the real Anthropic + OpenAI upstream keys (root-only file).
       sudo \$EDITOR /etc/ai-fortress/upstream.env
  2. Log out and back in (or 'newgrp fortress') so $INVOKER's group membership
     takes effect — required for sudo -n /usr/local/sbin/fortress-mint to work.
  3. Run the activation step: sudo bash $REPO_DIR/start-phase1.sh
EOF
